# Generated by Django 5.0.4 on 2024-04-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothset',
            old_name='tabel_num',
            new_name='person',
        ),
    ]
